variables:
  IMAGE_NAME: fr3m3n/front-vanilla
  IMAGE_TAG: front-1.1

stages:
  - test
  - build
  - deploy

    # - apt-get install sudo
    # - apt-get install wget

test_terraform:
  stage: test
  image: ubuntu:20.04
  before_script:
    - apt-get update && apt-get upgrade
    - apt-get -y -o StrictHostKeyChecking=no install wget
    - apt-get install sudo
    - apt-get -y -o StrictHostKeyChecking=no install gnupg
    - wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    - sudo apt install terraform
  script:
    - terraform --version

build_image:
  stage: build
  image: docker:24-cli
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy_aws:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script: 
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@54.162.20.52 "
        sudo docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
        sudo docker ps -aq | xargs sudo docker stop | xargs sudo docker rm &&
        sudo docker run -d -p 80:80 $IMAGE_NAME:$IMAGE_TAG"

        # sudo docker ps -aq | xargs sudo docker stop | xargs sudo docker rm &&
