stages:
  - prepare_tf   # [Terraform] pipelines
  - validate_tf
  - plan_tf
  - deploy_tf
  - destroy_tf
  - configure_infra # [Ansible] pipeline
  - build_image     # [Frontend] pipelines
  - deploy_image

include:
  - local: '/pipelines/deploy_infrastructure.yml'
  - local: '/pipelines/configure_infrastructure.yml'
  - local: '/pipelines/deliver_frontend.yml'
