# include:
#   - local: '/pipelines/terraform.yml'
variables:
  TF_IMAGE: hashicorp/terraform:latest
  TF_PATH: IaC/provisioning

terraform-plan:
  image: 
    name: ${TF_IMAGE}
    entrypoint: [""]
  before_script:
  - cd ${TF_PATH}
  script:
    - terraform init
    - terraform plan
