variables:
  IMAGE_NAME: fr3m3n/front-vanilla
  IMAGE_TAG: front-1.0

build_image:
  image: docker:24.0.7-cli
  services:
    - docker:24.0.7-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push -t $IMAGE_NAME:$IMAGE_TAG