image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest

variables:
  TF_STATE_NAME: dynamic-resume
  TF_ROOT: IaC/provisioning
  TF_ADDRESS: https://gitlab.com/api/v4/projects/51944352/terraform/state/$TF_STATE_NAME


before_script:
  - cd $TF_ROOT
  - sh ./init.sh


stages:
  - prepare
  - validate
  - plan
  - deploy
  - destroy

terraform_init:
  stage: prepare
  script:
    - gitlab-terraform init
  resource_group: $TF_STATE_NAME # limit the concurrency of jobs to access shared resource
  rules:
  - if: '$CI_COMMIT_BRANCH == "main"'
    changes:
      - ${TF_ROOT}/main.tf

terraform_validate:
  stage: validate
  script:
    - gitlab-terraform init
    - gitlab-terraform validate
  resource_group: $TF_STATE_NAME
  rules:
  - if: '$CI_COMMIT_BRANCH == "main"'
    changes:
      - ${TF_ROOT}/main.tf

terraform_plan:
  stage: plan
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  resource_group: $TF_STATE_NAME
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json
  rules:
  - if: '$CI_COMMIT_BRANCH == "main"'
    changes:
      - ${TF_ROOT}/main.tf


deploy_aws_infrastructure:
  stage: deploy
  script:
    - gitlab-terraform apply
  resource_group: $TF_STATE_NAME
  dependencies:
    - terraform_plan
  rules:
  - if: '$CI_COMMIT_BRANCH == "main"'
    changes:
      - ${TF_ROOT}/main.tf
    when: manual # blocked

destroy_aws_infrastructure:
  stage: destroy
  script:
    - gitlab-terraform destroy -auto-approve
  resource_group: $TF_STATE_NAME
  dependencies:
    - terraform_plan
  rules:
  - if: '$CI_COMMIT_BRANCH == "main"'
    changes:
      - ${TF_ROOT}/main.tf
  when: manual
