image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest



variables:
  TF_STATE_NAME: dynamic-resume
  TF_ROOT: IaC/provisioning
  TF_ADDRESS: https://gitlab.com/api/v4/projects/51944352/terraform/state/$TF_STATE_NAME


before_script:
  - cd $TF_ROOT
  - sh ./init.sh


stages:
  - prepare
  - validate
  - plan
  - deploy
  - destroy

init:
  stage: prepare
  script:
    - gitlab-terraform init
  resource_group: $TF_STATE_NAME
  rules:
  - if: '$CI_COMMIT_BRANCH == "main"'
    changes:
      - ${TF_PATH}/main.tf

validate:
  stage: validate
  script:
    - gitlab-terraform init
    - gitlab-terraform validate
  resource_group: $TF_STATE_NAME
  rules:
  - if: '$CI_COMMIT_BRANCH == "main"'
    changes:
      - ${TF_PATH}/main.tf

plan:
  stage: plan
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  resource_group: $TF_STATE_NAME
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json
  rules:
  - if: '$CI_COMMIT_BRANCH == "main"'
    changes:
      - ${TF_PATH}/main.tf


deploy:
  stage: deploy
  script:
    - gitlab-terraform apply
  resource_group: $TF_STATE_NAME
  dependencies:
    - plan
  rules:
  - if: '$CI_COMMIT_BRANCH == "main"'
    changes:
      - ${TF_PATH}/main.tf
    when: manual

destroy:
  stage: destroy
  script:
    - gitlab-terraform destroy -auto-approve
  resource_group: $TF_STATE_NAME
  dependencies:
    - plan
  rules:
  - if: '$CI_COMMIT_BRANCH == "main"'
    changes:
      - ${TF_PATH}/main.tf
  when: manual
