image: registry.gitlab.com/gitlab-org/terraform-images/stable:latest
variables:
  TF_ROOT: IaC/provisioning
  TF_ADDRESS: https://gitlab.com/api/v4/projects/51944352/terraform/state/dynamic-resume

# cache:
#   key: example-production
#   paths:
#     - ${TF_ROOT}/.terraform

before_script:
  - cd ${TF_ROOT}
  - sh ./init.sh  # Calls your init.sh script


stages:
  - prepare
  - validate
  - plan
  - deploy
  - destroy

init:
  stage: prepare
  script:
    - gitlab-terraform init

validate:
  stage: validate
  script:
    - gitlab-terraform init
    - gitlab-terraform validate

plan:
  stage: plan
  script:
    - gitlab-terraform plan
    - gitlab-terraform plan-json
  artifacts:
    name: plan
    paths:
      - ${TF_ROOT}/plan.cache
    reports:
      terraform: ${TF_ROOT}/plan.json


deploy:
  stage: deploy
  script:
    - gitlab-terraform apply
  dependencies:
    - plan
  when: manual

destroy:
  stage: destroy
  script:
    - gitlab-terraform destroy -auto-approve
  dependencies:
    - plan
  when: manual
