stages:
  - validate
  - plan
  - apply
  - destroy

variables:
  TF_IMAGE: hashicorp/terraform:1.6.3
  TF_PATH: IaC/provisioning
  TF_STATE_NAME: default
  TERRAFORM_BACKEND_ADDRESS: https://gitlab.com/api/v4/projects/51944352/terraform/state/default
  TERRAFORM_BACKEND_LOCK_ADDRESS: https://gitlab.com/api/v4/projects/51944352/terraform/state/default/lock
  TERRAFORM_BACKEND_UNLOCK_ADDRESS: https://gitlab.com/api/v4/projects/51944352/terraform/state/default/lock

validate:
  stage: validate
  image: 
    name: ${TF_IMAGE}
    entrypoint: [""]
  before_script:
    - cd ${TF_PATH}
  script:
    - terraform init \
      -backend-config="address=${TERRAFORM_BACKEND_ADDRESS}" \
      -backend-config="lock_address=${TERRAFORM_BACKEND_LOCK_ADDRESS}" \
      -backend-config="unlock_address=${TERRAFORM_BACKEND_UNLOCK_ADDRESS}" \
      -backend-config="username=gitlab-ci-token" \
      -backend-config="password=${CI_JOB_TOKEN}"
    - terraform validate
  resource_group: ${TF_STATE_NAME} # limit the concurrency of jobs to access shared resource
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - ${TF_PATH}/main.tf

plan:
  stage: plan
  image: ${TF_IMAGE}
  before_script:
    - cd ${TF_PATH}
  script:
    - terraform plan -out=tfplan
  resource_group: ${TF_STATE_NAME} # limit the concurrency of jobs to access shared resource
  artifacts:
    paths:
      - ${TF_PATH}/tfplan
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - ${TF_PATH}/main.tf

apply:
  stage: apply
  image: ${TF_IMAGE}
  before_script:
    - cd ${TF_PATH}
  script:
    - terraform apply tfplan
  resource_group: ${TF_STATE_NAME} # limit the concurrency of jobs to access shared resource
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - ${TF_PATH}/main.tf
      when: manual

destroy:
  stage: destroy
  image: ${TF_IMAGE}
  before_script:
    - cd ${TF_PATH}
  script:
    - terraform destroy -auto-approve
  resource_group: ${TF_STATE_NAME} # limit the concurrency of jobs to access shared resource
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - ${TF_PATH}/main.tf
      when: manual
