stages:
  - validate
  - plan
  - apply
  - destroy

variables:
  TF_IMAGE: "$CI_TEMPLATE_REGISTRY_HOST/gitlab-org/terraform-images/releases/1.4:v1.0.0"
  TF_PATH: IaC/provisioning
  TF_STATE_NAME: default
  TF_ROOT: ${CI_PROJECT_DIR}/IaC/provisioning
  SECURE_FILES_DOWNLOAD_PATH: "./terraform"



validate:
  stage: validate
  image: docker:24-cli
  services:
    - docker:24-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - 'if [ -z "$CI_JOB_TOKEN" ]; then echo "CI_JOB_TOKEN is not set"; else echo "CI_JOB_TOKEN is set"; fi'
    - >
      docker run
      -e CI_JOB_TOKEN=${CI_JOB_TOKEN}
      -v $(pwd)/${TF_PATH}:/workspace
      -w /workspace
      hashicorp/terraform:1.6.3 init
    - >
      docker run
      -v $(pwd)/${TF_PATH}:/workspace
      -w /workspace
      hashicorp/terraform:1.6.3 plan -out=/workspace/plan.tfplan
  artifacts:
    paths:
      - ${TF_PATH}/plan.tfplan
  resource_group: ${TF_STATE_NAME} # limit the concurrency of jobs to access shared resource
  cache:
    untracked: true
    paths:
      - ${TF_PATH}
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - ${TF_PATH}/main.tf

plan:
  stage: plan
  image: ${TF_IMAGE}
  before_script:
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | sh
    - cd ${TF_ROOT}
  script:
    - gitlab-terraform plan #-out=tfplan
  resource_group: ${TF_STATE_NAME}
  # artifacts:
  #   paths:
  #     - tfplan
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - ${TF_PATH}/main.tf

apply:
  stage: apply
  image: ${TF_IMAGE}
  before_script:
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | sh
    - cd ${TF_ROOT}
  script:
    - gitlab-terraform plan-json
    - gitlab-terraform apply #tfplan
  resource_group: ${TF_STATE_NAME}
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - ${TF_PATH}/main.tf
      when: manual

destroy:
  stage: destroy
  image: ${TF_IMAGE}
  before_script:
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | sh
    - cd ${TF_ROOT}
  script:
    - gitlab-terraform destroy -auto-approve
  resource_group: ${TF_STATE_NAME}
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      changes:
        - ${TF_PATH}/main.tf
      when: manual
